// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using IntegrationSaturdayWeb101.Models;
using Newtonsoft.Json.Linq;

namespace IntegrationSaturdayWeb101.Models
{
    public static partial class PresenterCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Presenter> DeserializeJson(JToken inputObject)
        {
            IList<Presenter> deserializedObject = new List<Presenter>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Presenter presenter = new Presenter();
                presenter.DeserializeJson(iListValue);
                deserializedObject.Add(presenter);
            }
            return deserializedObject;
        }
    }
}
