// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using IntegrationSaturdayWeb101;
using IntegrationSaturdayWeb101.Models;
using Microsoft.Rest;

namespace IntegrationSaturdayWeb101
{
    public static partial class PresenterOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the IntegrationSaturdayWeb101.IPresenterOperations.
        /// </param>
        public static IList<Presenter> Get(this IPresenterOperations operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IPresenterOperations)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the IntegrationSaturdayWeb101.IPresenterOperations.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Presenter>> GetAsync(this IPresenterOperations operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<IntegrationSaturdayWeb101.Models.Presenter>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
